// SPDX-License-Identifier: GPL-2.0
//
// Copyright (c) 2021 MediaTek Inc.

#include <linux/io.h>
#include <linux/module.h>
#include "clkchk.h"

static const char * const off_pll_names[] = {
	"univ2pll",
	"msdcpll",
	"mmpll",
	"nnapll",
	"nna2pll",
	"adsppll",
	"mfgpll",
	"tvdpll",
	"apll1",
	"apll2",
	NULL
};

static const char * const all_clk_names[] = {
	"armpll_ll",
	"armpll_bl",
	"ccipll",
	"mainpll",
	"univ2pll",
	"msdcpll",
	"mmpll",
	"nnapll",
	"nna2pll",
	"adsppll",
	"mfgpll",
	"tvdpll",
	"apll1",
	"apll2",
	"mcu_armpll_ll_sel",
	"mcu_armpll_bl_sel",
	"mcu_armpll_bus_sel",
	"top_axi",
	"top_scp",
	"top_mfg",
	"top_camtg",
	"top_camtg1",
	"top_camtg2",
	"top_camtg3",
	"top_camtg4",
	"top_camtg5",
	"top_camtg6",
	"top_uart",
	"top_spi",
	"top_msdc5hclk",
	"top_msdc50_0",
	"top_msdc30_1",
	"top_audio",
	"top_aud_intbus",
	"top_aud_1",
	"top_aud_2",
	"top_aud_engen1",
	"top_aud_engen2",
	"top_disp_pwm",
	"top_sspm",
	"top_dxcc",
	"top_usb",
	"top_srck",
	"top_spm",
	"top_i2c",
	"top_pwm",
	"top_seninf",
	"top_seninf1",
	"top_seninf2",
	"top_seninf3",
	"top_aes_msdcfde",
	"top_pwrap_ulposc",
	"top_camtm",
	"top_venc",
	"top_cam",
	"top_img1",
	"top_ipe",
	"top_dpmaif",
	"top_vdec",
	"top_disp",
	"top_mdp",
	"top_audio_h",
	"top_ufs",
	"top_aes_fde",
	"top_audiodsp",
	"top_dsi_occ",
	"top_spmi_mst",
	"top_spinor",
	"top_nna",
	"top_nna1",
	"top_nna2",
	"top_ssusb_xhci",
	"top_ssusb_1p",
	"top_ssusb_xhci_1p",
	"top_wpe",
	"top_dpi",
	"top_u3_occ_250m",
	"top_u3_occ_500m",
	"top_adsp_bus",
	"apll_i2s0_mck_sel",
	"apll_i2s1_mck_sel",
	"apll_i2s2_mck_sel",
	"apll_i2s4_mck_sel",
	"apll_tdmout_mck_sel",
	"mainpll_d2",
	"mainpll_d2_d2",
	"mainpll_d2_d4",
	"mainpll_d2_d16",
	"mainpll_d3",
	"mainpll_d3_d2",
	"mainpll_d3_d4",
	"mainpll_d5",
	"mainpll_d5_d2",
	"mainpll_d5_d4",
	"mainpll_d7",
	"mainpll_d7_d2",
	"mainpll_d7_d4",
	"univpll_d2",
	"univpll_d2_d2",
	"univpll_d2_d4",
	"univpll_d3",
	"univpll_d3_d2",
	"univpll_d3_d4",
	"univpll_d3_d8",
	"univpll_d3_d32",
	"univpll_d5",
	"univpll_d5_d2",
	"univpll_d5_d4",
	"univpll_d7",
	"univpll_192m_d4",
	"univpll_192m_d8",
	"univpll_192m_d16",
	"univpll_192m_d32",
	"apll1_d2",
	"apll1_d4",
	"apll1_d8",
	"apll2_d2",
	"apll2_d4",
	"apll2_d8",
	"mmpll_d2",
	"tvdpll_d2",
	"tvdpll_d4",
	"tvdpll_d8",
	"tvdpll_d16",
	"tvdpll_d32",
	"msdcpll_d2",
	"ulposc1_d2",
	"ulposc1_d4",
	"ulposc1_d8",
	"ulposc1_d10",
	"ulposc1_d16",
	"ulposc1_d32",
	"adsppll_d2",
	"adsppll_d4",
	"adsppll_d8",
	"nnapll_d2",
	"nnapll_d4",
	"nnapll_d8",
	"nna2pll_d2",
	"f_bist2fpc_ck",
	"hd_466m_fmem_ck",
	"mpll",
	"apll12_div0",
	"apll12_div1",
	"apll12_div2",
	"apll12_div4",
	"apll12_div_tdmout_m",
	"infra_ao_pmic_tmr",
	"infra_ao_pmic_ap",
	"infra_ao_pmic_md",
	"infra_ao_pmic_conn",
	"infra_ao_sej",
	"infra_ao_apxgpt",
	"infra_ao_icusb",
	"infra_ao_gce",
	"infra_ao_therm",
	"infra_ao_i2c_ap",
	"infra_ao_i2c_ccu",
	"infra_ao_i2c_sspm",
	"infra_ao_i2c_rsv",
	"infra_ao_pwm_hclk",
	"infra_ao_pwm1",
	"infra_ao_pwm2",
	"infra_ao_pwm3",
	"infra_ao_pwm4",
	"infra_ao_pwm5",
	"infra_ao_pwm",
	"infra_ao_uart0",
	"infra_ao_uart1",
	"infra_ao_uart2",
	"infra_ao_gce_26m",
	"infra_ao_dma",
	"infra_ao_btif",
	"infra_ao_spi0",
	"infra_ao_msdc0",
	"infra_ao_msdcfde",
	"infra_ao_msdc1",
	"infra_ao_gcpu",
	"infra_ao_trng",
	"infra_ao_auxadc",
	"infra_ao_cpum",
	"infra_ao_ccif1_ap",
	"infra_ao_ccif1_md",
	"infra_ao_auxadc_md",
	"infra_ao_ap_dma",
	"infra_ao_xiu",
	"infra_ao_dapc",
	"infra_ao_ccif_ap",
	"infra_ao_debugtop",
	"infra_ao_audio",
	"infra_ao_ccif_md",
	"infra_ao_secore",
	"infra_ao_dxcc_ao",
	"infra_ao_imp_iic",
	"infra_ao_dramc26",
	"infra_ao_pwm_fbclk6",
	"infra_ao_ssusb_hclk",
	"infra_ao_disp_pwm",
	"infra_ao_cldmabclk",
	"infra_ao_audio26m",
	"infra_ao_ssusb_p1_hclk",
	"infra_ao_spi1",
	"infra_ao_i2c4",
	"infra_ao_mdtemp",
	"infra_ao_spi2",
	"infra_ao_spi3",
	"infra_ao_ssusb_ref",
	"infra_ao_ssusb_xhci",
	"infra_ao_ssusb_p1_ref",
	"infra_ao_ssusb_p1_xhci",
	"infra_ao_sspm",
	"infra_ao_ssusb_p1_sys",
	"infra_ao_i2c5",
	"infra_ao_i2c5a",
	"infra_ao_i2c5_imm",
	"infra_ao_i2c1a",
	"infra_ao_i2c1_imm",
	"infra_ao_i2c2a",
	"infra_ao_i2c2_imm",
	"infra_ao_spi4",
	"infra_ao_spi5",
	"infra_ao_cq_dma",
	"infra_ao_bist2fpc",
	"infra_ao_msdc0sf",
	"infra_ao_msdc1sf",
	"infra_ao_sspm_26m",
	"infra_ao_sspm_32k",
	"infra_ao_i2c6",
	"infra_ao_ap_msdc0",
	"infra_ao_md_msdc0",
	"infra_ao_msdc0_clk",
	"infra_ao_msdc1_clk",
	"infra_ao_sej_f13m_ck",
	"infra_ao_aes_top0_bclk",
	"infra_ao_mcu_pm_bclk",
	"infra_ao_ccif2_ap",
	"infra_ao_ccif2_md",
	"infra_ao_ccif3_ap",
	"infra_ao_ccif3_md",
	"infra_ao_fadsp_26m",
	"infra_ao_fadsp_32k",
	"infra_ao_ccif4_ap",
	"infra_ao_ccif4_md",
	"infra_ao_fadsp_ck",
	"infra_ao_flashif_133m",
	"infra_ao_flashif_66m",
	"adsp_core",
	"adsp_coredbg_en",
	"adsp_timer_en",
	"adsp_dma_en",
	"adsp_uart_en",
	"adsp_uart_bclk",
	"nna0_enballe",
	"nna1_enballe",
	"nna2_enballe",
	"nna_26m_clk",
	"nna_emi_clk",
	"nna_axi_clk",
	"imp_iic_wrap_ap_clock_i2c6",
	"aud_afe",
	"aud_22m",
	"aud_24m",
	"aud_apll2_tuner",
	"aud_apll_tuner",
	"aud_tdm_ck",
	"aud_adc",
	"aud_dac",
	"aud_dac_predis",
	"aud_tml",
	"aud_nle",
	"aud_i2s1_bclk",
	"aud_i2s2_bclk",
	"aud_i2s3_bclk",
	"aud_i2s4_bclk",
	"aud_connsys_i2s_asrc",
	"aud_general1_asrc",
	"aud_general2_asrc",
	"aud_dac_hires",
	"aud_adc_hires",
	"aud_adc_hires_tml",
	"aud_adda6_adc",
	"aud_adda6_adc_hires",
	"aud_3rd_dac",
	"aud_3rd_dac_predis",
	"aud_3rd_dac_tml",
	"aud_3rd_dac_hires",
	"aud_etdm_in1_bclk",
	"aud_etdm_out1_bclk",
	"msdc_axi_wrap_cken",
	"usb3_sif_dma_bus_ck",
	"usb3_sif_ssusb_ip_dma_bus_ck",
	"usb3_sif_ssusb_u2_port_dis",
	"usb3_sif_ssusb_u3_port_dis",
	"mipi_tx0_mipi_tx_test_en",
	"mfg_bg3d",
	"mm_disp_mutex0",
	"mm_apb_mm_bus",
	"mm_disp_ovl0",
	"mm_disp_rdma0",
	"mm_disp_ovl0_2l",
	"mm_disp_wdma0",
	"mm_disp_rsz0",
	"mm_disp_aal0",
	"mm_disp_ccorr0",
	"mm_disp_color0",
	"mm_smi_infra",
	"mm_disp_dsc_wrap0",
	"mm_disp_gamma0",
	"mm_disp_postmask0",
	"mm_disp_dither0",
	"mm_smi_common",
	"mm_dsi0",
	"mm_disp_fake_eng0",
	"mm_disp_fake_eng1",
	"mm_smi_gals",
	"mm_smi_iommu",
	"mm_dsi0_dsi_domain",
	"mm_disp_26m_ck",
	"wpe",
	"wpe_smi_larb8",
	"wpe_sys_event_tx",
	"wpe_smi_larb8_p_en",
	"img1_larb9_img1",
	"img1_larb10_img1",
	"img1_dip",
	"img1_gals_img1",
	"img2_larb9_img2",
	"img2_larb10_img2",
	"img2_mfb",
	"img2_wpe",
	"img2_mss",
	"img2_gals_img2",
	"vdec_larb1_cken",
	"vdec_lat_cken",
	"vdec_lat_active",
	"vdec_lat_cken_eng",
	"vdec_mini_mdp_cken_cfg_rg",
	"vdec_cken",
	"vdec_active",
	"vdec_cken_eng",
	"venc_cke0_larb",
	"venc_cke1_venc",
	"venc_cke2_jpgenc",
	"venc_cke5_gals",
	"cam_larb13",
	"cam_dfp_vad",
	"cam_larb14",
	"cam",
	"camtg",
	"cam_seninf",
	"camsv1",
	"camsv2",
	"camsv3",
	"cam_ccu0",
	"cam_ccu1",
	"cam_mraw0",
	"cam_fake_eng",
	"cam_ccu_gals",
	"cam2mm_gals",
	"cam_rawa_larbx_rawa",
	"cam_rawa",
	"cam_rawa_camtg_rawa",
	"cam_rawb_larbx_rawb",
	"cam_rawb",
	"cam_rawb_camtg_rawb",
	"mdp_rdma0",
	"mdp_tdshp0",
	"mdp_img_dl_async0",
	"mdp_img_dl_async1",
	"mdp_smi0",
	"mdp_apb_bus",
	"mdp_wrot0",
	"mdp_rsz0",
	"mdp_hdr0",
	"mdp_mutex0",
	"mdp_wrot1",
	"mdp_rsz1",
	"mdp_fake_eng0",
	"mdp_aal0",
	"mdp_img_dl_rel0_as0",
	"mdp_img_dl_rel1_as1",
	"ipe_larb19",
	"ipe_larb20",
	"ipe_smi_subcom",
	"ipe_fd",
	"ipe_fe",
	"ipe_rsc",
	"ipe_dpe",
	"ipe_gals_ipe",
	/* end */
	NULL
};

static void __iomem *scpsys_base, *pwr_sta, *pwr_sta_2nd;

static void dump_pwr_status(void)
{
	static const char * const pwr_names[] = {
		[0] = "WPE",
		[1] = "CONN_ON",
		[2] = "MFG0",
		[3] = "MFG1",
		[4] = "MFG2",
		[5] = "MFG3",
		[6] = "CSIRX_TOP",
		[7] = "MGF5",
		[8] = "MFG6",
		[9] = "IFR",
		[10] = "ADSP_INFRA",
		[11] = "DPY",
		[12] = "DRAMC_MD32",
		[13] = "IMG",
		[14] = "IMG2",
		[15] = "IPE",
		[16] = "VDEC",
		[17] = "ADSP_AO",
		[18] = "VENC",
		[19] = "SSUSB_P1",
		[20] = "SSUSB",
		[21] = "DIS",
		[22] = "AUDIO",
		[23] = "CAM",
		[24] = "CAM_RAWA",
		[25] = "CAM_RAWB",
		[26] = "NNA3",
		[27] = "NNA0",
		[28] = "NNA1",
		[29] = "NNA2",
		[30] = "NNA",
		[31] = "ADSP_TOP",
		[32] = NULL,
	};

	u32 pwr_status_val = 0, pwr_status_2nd_val = 0;
	u8 i = 0;

	if (scpsys_base == NULL || pwr_sta == NULL || pwr_sta_2nd == NULL)
		return;

	pwr_status_val = readl(pwr_sta);
	pwr_status_2nd_val = readl(pwr_sta_2nd);

	pr_info("PWR_STATUS: 0x%08x\n", pwr_status_val);
	pr_info("PWR_STATUS_2ND: 0x%08x\n", pwr_status_2nd_val);

	for (i = 0; i < 32; i++) {
		const char *st = (pwr_status_val & BIT(i)) != 0U ? "ON" : "OFF";
		const char *st_2nd = (pwr_status_2nd_val & BIT(i)) != 0U ? "ON" : "OFF";

		if (!strcmp(st, "ON") && !strcmp(st_2nd, "ON"))
			pr_info("[%2d]: %3s: %s\n", i, st, pwr_names[i]);
	}
}

static const char * const compatible[] = {"mediatek,mt8186", NULL};

static struct clkchk_cfg_t cfg = {
	.aee_excp_on_fail = false,
	.warn_on_fail = true,
	.compatible = compatible,
	.off_pll_names = off_pll_names,
	.all_clk_names = all_clk_names,
	.dump_pwr_status = dump_pwr_status,
};

static int __init clkchk_platform_init(void)
{
	scpsys_base = ioremap(0x10006000, PAGE_SIZE);
	pwr_sta = scpsys_base + 0x16C;
	pwr_sta_2nd = scpsys_base + 0x170;

	return clkchk_init(&cfg);
}

static void __exit clkchk_platform_exit(void)
{
}

module_init(clkchk_platform_init);
module_exit(clkchk_platform_exit);
MODULE_LICENSE("GPL");
